<?php

namespace app\models;

class Constant extends BaseConstant
{

    /**
     * 组织
     */
    const ORGANIZATION_SHU_KE = 1; // 数客
    const ORGANIZATION_LIANG_ZI = 2; // 量子
    const ORGANIZATION_KUA_KE = 3; // 跨客
    const ORGANIZATION_YUAN_ZI = 4; // 原子
    const ORGANIZATION_A_ER_FA = 5; // 阿尔法
    const ORGANIZATION_BEI_TA = 6; // 贝塔
    const ORGANIZATION_LIU_LIANG = 7; // 流量
    const ORGANIZATION_MA_YI = 8; // 蚂蚁
    const ORGANIZATION_NUO_YA = 9; // 诺亚
    const ORGANIZATION_SAN_TI = 10; // 三体
    const ORGANIZATION_XING_QIU_CAN = 11; // 星球仓
    const ORGANIZATION_SHEN_ZHOU_WU_LIU = 12; // 神州物流
    const ORGANIZATION_PAI_TE = 13; // 派特
    const ORGANIZATION_OTHER = 0; // 其他

    /**
     * 平台
     */
    const PLATFORM_SHOPIFY = 1;
    const PLATFORM_AMAZON = 2;
    const PLATFORM_EBAY = 3;
    const PLATFORM_WISH = 4;
    const PLATFORM_TOPHATTER = 5;
    const PLATFORM_ALIEXPRESS = 6;

    /**
     * 第三方平台
     */
    const THIRD_PARTY_PLATFORM_DIAN_XIAO_MI = 1; // 店小秘
    const THIRD_PARTY_PLATFORM_TONG_TOOL = 2; // 通途
    const THIRD_PARTY_PLATFORM_GERPGO = 3; // 积加
    const THIRD_PARTY_PLATFORM_SHOPIFY = 4; // Shopify

    /**
     * 地区
     */
    const REGION_EUROPE = 1; // 欧洲
    const REGION_NORTH_AMERICA = 2; // 北美
    const REGION_SOUTH_AMERICA = 3; // 南美
    const REGION_ASIA = 4; // 亚洲
    const REGION_OCEANIA = 5; // 大洋洲
    const REGION_AFRICA = 6; // 非洲
    const REGION_OTHER = 0; // 其他

    /**
     * 店小秘平台订单状态
     */
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_UNKNOWN = 0; // 未知
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_WEI_FU_KUAN = 1; // 未付款
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_FENG_KONG_ZHONG = 2; // 风控中
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_DAI_SHEN_HE = 3; // 待审核
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_DAI_CHU_LI = 4; // 待处理
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_YI_CHU_LI = 5; // 已处理
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_DAI_DA_DANG_YOU_HUO = 6; // 待打单（有货）
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_DAI_DA_DANG_QUE_HUO = 7; // 待打单（缺货）
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_DAI_DA_DANG_YOU_YI_CHANG = 8; // 待打单（有异常）
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_YI_JIAO_YUN = 9; // 已交运
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_TUI_KUAN = 10; // 已退款
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_YI_HU_LUE = 11; // 已忽略
    const THIRD_PARTY_PLATFORM_DXM_ORDER_STATUS_YI_WAN_CHENG = 12; // 已完成

    /**
     * 店小秘平台包裹状态
     */
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_UNKNOWN = 0; // 未知
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_WEI_FU_KUAN = 1; // 未付款
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_FENG_KONG_ZHONG = 2; // 风控中
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_DAI_SHEN_HE = 3; // 待审核
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_DAI_CHU_LI = 4; // 待处理
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_YI_CHU_LI = 5; // 已处理
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_DAI_DA_DANG_YOU_HUO = 6; // 待打单（有货）
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_DAI_DA_DANG_QUE_HUO = 7; // 待打单（缺货）
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_DAI_DA_DANG_YOU_YI_CHANG = 8; // 待打单（有异常）
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_YI_JIAO_YUN = 9; // 已交运
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_TUI_KUAN = 10; // 已退款
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_YI_HU_LUE = 11; // 已忽略
    const THIRD_PARTY_PLATFORM_DXM_PACKAGE_STATUS_YI_WAN_CHENG = 12; // 已完成

    /**
     * 通途平台订单状态
     */
    const THIRD_PARTY_PLATFORM_TONG_TOOL_ORDER_STATUS_UNKNOWN = 0; // 未知

    /**
     * 通途平台包裹状态
     */
    const THIRD_PARTY_PLATFORM_TONG_TOOL_PACKAGE_STATUS_UNKNOWN = 0; // 未知

    /**
     * 积加 ERP 订单状态
     */
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_UNKNOWN = 0; // 无状态
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_WEI_FU_KUAN = 1; // 未付款
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_WEI_FA_HUO = 2; // 未发货
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_JIAN_HUO_ZHONG = 3; // 拣货中
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_YI_FA_HUO = 4; // 已发货
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_YI_QU_XIAO = 5; // 已取消
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_YU_DING = 6; // 预订订单
    const THIRD_PARTY_PLATFORM_GERPGO_ORDER_STATUS_BU_FENG_FA_HUO = 7; // 部分发货

    /**
     * shopify 订单支付状态
     */
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_UNKNOWN = 0; // 未知
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_AUTHORIZED = 1; // 已授权
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_PAID = 2; //　已付费
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_PARTIALLY_PARTIALLY_REFUNDED = 3; // 部分退款
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_PARTIALLY_PAID = 4; // 部分付款
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_PENDING = 5; // 待定
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_PARTIALLY_REFUNDED = 6; // 已退款
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_UNPAID = 7; // 未付款
    const THIRD_PARTY_PLATFORM_FINANCIAL_STATUS_VOIDED = 8; // 无效

    /**
     * shopify 订单完成状态
     */
    const THIRD_PARTY_PLATFORM_FULFILLMENT_STATUS_UNKNOWN = 0; // 未知
    const THIRD_PARTY_PLATFORM_FULFILLMENT_STATUS_PARTIAL = 1; // 部分完成
    const THIRD_PARTY_PLATFORM_FULFILLMENT_STATUS_UNFULFILLED = 2; // 未完成
    const THIRD_PARTY_PLATFORM_FULFILLMENT_STATUS_FULFILLED = 3; // 完成

}